SET NOCOUNT ON;

PRINT '--- Datum ---';
SELECT TOP 10 Datum FROM TAGPLANTERMIN WHERE Datum IS NOT NULL ORDER BY Datum DESC;

PRINT '--- MutDatum ---';
SELECT TOP 10 MutDatum FROM TAGPLANTERMIN WHERE MutDatum IS NOT NULL ORDER BY MutDatum DESC;

PRINT '--- OrgDatum ---';
SELECT TOP 10 OrgDatum FROM TAGPLANTERMIN WHERE OrgDatum IS NOT NULL ORDER BY OrgDatum DESC;

PRINT '--- InterDownDatum ---';
SELECT TOP 10 InterDownDatum FROM TAGPLANTERMIN WHERE InterDownDatum IS NOT NULL ORDER BY InterDownDatum DESC;

PRINT '--- ErstelltDatum ---';
SELECT TOP 10 ErstelltDatum FROM TAGPLANTERMIN WHERE ErstelltDatum IS NOT NULL ORDER BY ErstelltDatum DESC;

PRINT '--- OAErstelltDatum ---';
SELECT TOP 10 OAErstelltDatum FROM TAGPLANTERMIN WHERE OAErstelltDatum IS NOT NULL ORDER BY OAErstelltDatum DESC;

PRINT '--- OAMutDatum ---';
SELECT TOP 10 OAMutDatum FROM TAGPLANTERMIN WHERE OAMutDatum IS NOT NULL ORDER BY OAMutDatum DESC;
