PRINT '--- Zähler ---'
SELECT DISTINCT TOP 10 Zähler FROM TAGPLANTERMIN WHERE Zähler IS NOT NULL;
PRINT '--- FK_BehOrt ---'
SELECT DISTINCT TOP 10 FK_BehOrt FROM TAGPLANTERMIN WHERE FK_BehOrt IS NOT NULL;
PRINT '--- FK_Behandler ---'
SELECT DISTINCT TOP 10 FK_Behandler FROM TAGPLANTERMIN WHERE FK_Behandler IS NOT NULL;
PRINT '--- FK_Patient ---'
SELECT DISTINCT TOP 10 FK_Patient FROM TAGPLANTERMIN WHERE FK_Patient IS NOT NULL;
PRINT '--- FK_Recall ---'
SELECT DISTINCT TOP 10 FK_Recall FROM TAGPLANTERMIN WHERE FK_Recall IS NOT NULL;
PRINT '--- Beschreibung ---'
SELECT DISTINCT TOP 10 Beschreibung FROM TAGPLANTERMIN WHERE Beschreibung IS NOT NULL;
PRINT '--- Datum ---'
SELECT DISTINCT TOP 10 Datum FROM TAGPLANTERMIN WHERE Datum IS NOT NULL;
PRINT '--- VonZeit ---'
SELECT DISTINCT TOP 10 VonZeit FROM TAGPLANTERMIN WHERE VonZeit IS NOT NULL;
PRINT '--- BisZeit ---'
SELECT DISTINCT TOP 10 BisZeit FROM TAGPLANTERMIN WHERE BisZeit IS NOT NULL;
PRINT '--- Privat ---'
SELECT DISTINCT TOP 10 Privat FROM TAGPLANTERMIN WHERE Privat IS NOT NULL;
PRINT '--- Voraussichtlich ---'
SELECT DISTINCT TOP 10 Voraussichtlich FROM TAGPLANTERMIN WHERE Voraussichtlich IS NOT NULL;
PRINT '--- Farbe ---'
SELECT DISTINCT TOP 10 Farbe FROM TAGPLANTERMIN WHERE Farbe IS NOT NULL;
PRINT '--- Icon ---'
SELECT DISTINCT TOP 10 Icon FROM TAGPLANTERMIN WHERE Icon IS NOT NULL;
PRINT '--- ProvPatient ---'
SELECT DISTINCT TOP 10 ProvPatient FROM TAGPLANTERMIN WHERE ProvPatient IS NOT NULL;
PRINT '--- FK_TagPlanTerminKategorie ---'
SELECT DISTINCT TOP 10 FK_TagPlanTerminKategorie FROM TAGPLANTERMIN WHERE FK_TagPlanTerminKategorie IS NOT NULL;
PRINT '--- Periodisch ---'
SELECT DISTINCT TOP 10 Periodisch FROM TAGPLANTERMIN WHERE Periodisch IS NOT NULL;
PRINT '--- Status ---'
SELECT DISTINCT TOP 10 Status FROM TAGPLANTERMIN WHERE Status IS NOT NULL;
PRINT '--- MutDatum ---'
SELECT DISTINCT TOP 10 MutDatum FROM TAGPLANTERMIN WHERE MutDatum IS NOT NULL;
PRINT '--- Erstellt ---'
SELECT DISTINCT TOP 10 Erstellt FROM TAGPLANTERMIN WHERE Erstellt IS NOT NULL;
PRINT '--- Bemerkung ---'
-- SELECT DISTINCT TOP 10 Bemerkung FROM TAGPLANTERMIN WHERE Bemerkung IS NOT NULL;
PRINT '--- OrgDatum ---'
SELECT DISTINCT TOP 10 OrgDatum FROM TAGPLANTERMIN WHERE OrgDatum IS NOT NULL;
PRINT '--- VorlaufZeit ---'
SELECT DISTINCT TOP 10 VorlaufZeit FROM TAGPLANTERMIN WHERE VorlaufZeit IS NOT NULL;
PRINT '--- Folge ---'
SELECT DISTINCT TOP 10 Folge FROM TAGPLANTERMIN WHERE Folge IS NOT NULL;
PRINT '--- MutBehandler ---'
SELECT DISTINCT TOP 10 MutBehandler FROM TAGPLANTERMIN WHERE MutBehandler IS NOT NULL;
PRINT '--- MutBeschreibung ---'
SELECT DISTINCT TOP 10 MutBeschreibung FROM TAGPLANTERMIN WHERE MutBeschreibung IS NOT NULL;
PRINT '--- AnmeldeZeit ---'
SELECT DISTINCT TOP 10 AnmeldeZeit FROM TAGPLANTERMIN WHERE AnmeldeZeit IS NOT NULL;
PRINT '--- Wartezimmer ---'
SELECT DISTINCT TOP 10 Wartezimmer FROM TAGPLANTERMIN WHERE Wartezimmer IS NOT NULL;
PRINT '--- InterDownDatum ---'
SELECT DISTINCT TOP 10 InterDownDatum FROM TAGPLANTERMIN WHERE InterDownDatum IS NOT NULL;
PRINT '--- Abgesagt ---'
SELECT DISTINCT TOP 10 Abgesagt FROM TAGPLANTERMIN WHERE Abgesagt IS NOT NULL;
PRINT '--- nichtDrucken ---'
SELECT DISTINCT TOP 10 nichtDrucken FROM TAGPLANTERMIN WHERE nichtDrucken IS NOT NULL;
PRINT '--- TagPlanTerminAutoSMS ---'
SELECT DISTINCT TOP 10 TagPlanTerminAutoSMS FROM TAGPLANTERMIN WHERE TagPlanTerminAutoSMS IS NOT NULL;
PRINT '--- ErstelltDatum ---'
SELECT DISTINCT TOP 10 ErstelltDatum FROM TAGPLANTERMIN WHERE ErstelltDatum IS NOT NULL;
PRINT '--- OA_TerminID ---'
SELECT DISTINCT TOP 10 OA_TerminID FROM TAGPLANTERMIN WHERE OA_TerminID IS NOT NULL;
PRINT '--- OA_Status ---'
SELECT DISTINCT TOP 10 OA_Status FROM TAGPLANTERMIN WHERE OA_Status IS NOT NULL;
PRINT '--- SMSManuellVersandt ---'
SELECT DISTINCT TOP 10 SMSManuellVersandt FROM TAGPLANTERMIN WHERE SMSManuellVersandt IS NOT NULL;
PRINT '--- eMailManuellVersandt ---'
SELECT DISTINCT TOP 10 eMailManuellVersandt FROM TAGPLANTERMIN WHERE eMailManuellVersandt IS NOT NULL;
PRINT '--- Erinnerung ---'
SELECT DISTINCT TOP 10 Erinnerung FROM TAGPLANTERMIN WHERE Erinnerung IS NOT NULL;
PRINT '--- OATerminID ---'
SELECT DISTINCT TOP 10 OATerminID FROM TAGPLANTERMIN WHERE OATerminID IS NOT NULL;
PRINT '--- OABemerkung ---'
-- SELECT DISTINCT TOP 10 OABemerkung FROM TAGPLANTERMIN WHERE OABemerkung IS NOT NULL;
PRINT '--- Dokumente ---'
-- SELECT DISTINCT TOP 10 Dokumente FROM TAGPLANTERMIN WHERE Dokumente IS NOT NULL;
PRINT '--- Herkunft ---'
SELECT DISTINCT TOP 10 Herkunft FROM TAGPLANTERMIN WHERE Herkunft IS NOT NULL;
PRINT '--- __TS ---'
SELECT DISTINCT TOP 10 __TS FROM TAGPLANTERMIN WHERE __TS IS NOT NULL;
PRINT '--- TerminLinkID ---'
SELECT DISTINCT TOP 10 TerminLinkID FROM TAGPLANTERMIN WHERE TerminLinkID IS NOT NULL;
PRINT '--- eMailAuto ---'
SELECT DISTINCT TOP 10 eMailAuto FROM TAGPLANTERMIN WHERE eMailAuto IS NOT NULL;
PRINT '--- AbsageText ---'
SELECT DISTINCT TOP 10 AbsageText FROM TAGPLANTERMIN WHERE AbsageText IS NOT NULL;
PRINT '--- OATerminvorgabeID ---'
SELECT DISTINCT TOP 10 OATerminvorgabeID FROM TAGPLANTERMIN WHERE OATerminvorgabeID IS NOT NULL;
PRINT '--- OAProvPatient ---'
SELECT DISTINCT TOP 10 OAProvPatient FROM TAGPLANTERMIN WHERE OAProvPatient IS NOT NULL;
PRINT '--- OAErstelltDatum ---'
SELECT DISTINCT TOP 10 OAErstelltDatum FROM TAGPLANTERMIN WHERE OAErstelltDatum IS NOT NULL;
PRINT '--- OAMutDatum ---'
SELECT DISTINCT TOP 10 OAMutDatum FROM TAGPLANTERMIN WHERE OAMutDatum IS NOT NULL;
PRINT '--- OAMutHerkunft ---'
SELECT DISTINCT TOP 10 OAMutHerkunft FROM TAGPLANTERMIN WHERE OAMutHerkunft IS NOT NULL;
PRINT '--- FK_OAPraxis ---'
SELECT DISTINCT TOP 10 FK_OAPraxis FROM TAGPLANTERMIN WHERE FK_OAPraxis IS NOT NULL;

